package main

// DO NOT MODIFY: generated by github.com/ttacon/toml2cli
// If you need to make changes, update the toml config and then regenerate
// this file.

import (
	"log"
	"os"

	cli "github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Name = "mirrorfs"
	app.Usage = "Tool for mirroring a filesystem"

	app.Commands = []*cli.Command{
		&cli.Command{
			Description: "Run a mirrored mount",
			Name:        "run",
			Action:      mirrorFunc,
			Aliases:     []string{"r"},
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:    "mount",
					Aliases: []string{"mnt"},
				},
				&cli.StringFlag{
					Name:    "mirror",
					Aliases: []string{"mirr"},
				},
				&cli.StringFlag{
					Name:    "logLevel",
					Aliases: []string{"ll"},
				},
			},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
